# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import aforo_pb2 as aforo__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in aforo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AforoServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSeccion = channel.unary_unary(
                '/aforo.v1.AforoService/GetSeccion',
                request_serializer=aforo__pb2.GetSeccionRequest.SerializeToString,
                response_deserializer=aforo__pb2.SeccionResponse.FromString,
                _registered_method=True)
        self.ListSecciones = channel.unary_unary(
                '/aforo.v1.AforoService/ListSecciones',
                request_serializer=aforo__pb2.ListSeccionesRequest.SerializeToString,
                response_deserializer=aforo__pb2.ListSeccionesResponse.FromString,
                _registered_method=True)
        self.ListEventos = channel.unary_unary(
                '/aforo.v1.AforoService/ListEventos',
                request_serializer=aforo__pb2.ListEventosRequest.SerializeToString,
                response_deserializer=aforo__pb2.ListEventosResponse.FromString,
                _registered_method=True)
        self.VenderEntrada = channel.unary_unary(
                '/aforo.v1.AforoService/VenderEntrada',
                request_serializer=aforo__pb2.VenderEntradaRequest.SerializeToString,
                response_deserializer=aforo__pb2.VenderEntradaResponse.FromString,
                _registered_method=True)
        self.AnularEntrada = channel.unary_unary(
                '/aforo.v1.AforoService/AnularEntrada',
                request_serializer=aforo__pb2.AnularEntradaRequest.SerializeToString,
                response_deserializer=aforo__pb2.AnularEntradaResponse.FromString,
                _registered_method=True)


class AforoServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetSeccion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSecciones(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEventos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VenderEntrada(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnularEntrada(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AforoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSeccion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSeccion,
                    request_deserializer=aforo__pb2.GetSeccionRequest.FromString,
                    response_serializer=aforo__pb2.SeccionResponse.SerializeToString,
            ),
            'ListSecciones': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSecciones,
                    request_deserializer=aforo__pb2.ListSeccionesRequest.FromString,
                    response_serializer=aforo__pb2.ListSeccionesResponse.SerializeToString,
            ),
            'ListEventos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEventos,
                    request_deserializer=aforo__pb2.ListEventosRequest.FromString,
                    response_serializer=aforo__pb2.ListEventosResponse.SerializeToString,
            ),
            'VenderEntrada': grpc.unary_unary_rpc_method_handler(
                    servicer.VenderEntrada,
                    request_deserializer=aforo__pb2.VenderEntradaRequest.FromString,
                    response_serializer=aforo__pb2.VenderEntradaResponse.SerializeToString,
            ),
            'AnularEntrada': grpc.unary_unary_rpc_method_handler(
                    servicer.AnularEntrada,
                    request_deserializer=aforo__pb2.AnularEntradaRequest.FromString,
                    response_serializer=aforo__pb2.AnularEntradaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aforo.v1.AforoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aforo.v1.AforoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AforoService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSeccion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aforo.v1.AforoService/GetSeccion',
            aforo__pb2.GetSeccionRequest.SerializeToString,
            aforo__pb2.SeccionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSecciones(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aforo.v1.AforoService/ListSecciones',
            aforo__pb2.ListSeccionesRequest.SerializeToString,
            aforo__pb2.ListSeccionesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEventos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aforo.v1.AforoService/ListEventos',
            aforo__pb2.ListEventosRequest.SerializeToString,
            aforo__pb2.ListEventosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VenderEntrada(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aforo.v1.AforoService/VenderEntrada',
            aforo__pb2.VenderEntradaRequest.SerializeToString,
            aforo__pb2.VenderEntradaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnularEntrada(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aforo.v1.AforoService/AnularEntrada',
            aforo__pb2.AnularEntradaRequest.SerializeToString,
            aforo__pb2.AnularEntradaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
